#!/bin/sh
set -e

# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          garageDoorService
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Garage Door Service
### END INIT INFO

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
case "$1" in
  start)
	log_daemon_msg "Starting Garage Door Service" "garageDoorService" || true
	if start-stop-daemon --start --background --quiet --oknodo --make-pidfile --pidfile /var/run/garageDoorService.pid \
            --startas /bin/bash -- -c "exec /usr/sbin/garageDoorService.py >> /var/log/garageDoor.log 2>&1"; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping Garage Door Service" "garageDoorService" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/garageDoorService.pid; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  restart)
	log_daemon_msg "Restarting Garage Door Service" "garageDoorService" || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/garageDoorService.pid
	if start-stop-daemon --start --background --quiet --oknodo --make-pidfile --pidfile /var/run/garageDoorService.pid \
            --startas /bin/bash -- -c "exec /usr/sbin/garageDoorService.py >> /var/log/garageDoor.log 2>&1"; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  *)
	log_action_msg "Usage: /etc/init.d/garageDoorService {start|stop|restart}" || true
	exit 1
esac

exit 0
